steps:
  # Step 1: Build the API Docker image and push it to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bigquerysandbox-368012/api:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bigquerysandbox-368012/api:latest']

  # Step 2: SSH into the Compute Engine instance and deploy the services
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh instance-20241127-064052 \
        --zone us-central1-a \
        --command "sudo mkdir -p /app && sudo chmod 777 /app"
        
        gcloud compute scp docker-compose.yml instance-20241127-064052:/app --zone $ZONE
        
        gcloud compute ssh instance-20241127-064052 \
        --zone us-central1-a \
        --command 'cd /app && docker-compose down && docker-compose up -d'
